### ISSUE TITLE
Clean up TF 0.12 warnings

### ISSUE THREAD

**Issue by davidski** [cloudposse/terraform-aws-ssm-parameter-store#11]
Thanks for creating and maintaining this module!

With the current TF 0.12.16 release, warnings are now being thrown on quoted literals. While this module still works under current TF0.12, it throws a lot of warnings and with multiple instantiations that make the output really hard to digest. Would love to see a refresh of this to current TF 0.12 syntax!

**Comment by deadlysyn** [comment]
Was almost ready to fix this myself, the noticed there are already a couple PRs taking care of it. Any reason this isn't being merged? Is there a better way/another module for this I should be aware of?

**Comment by osterman** [comment]
We are currently only merging PRs for HCL2 that have terratests. Most modules have been upgraded but some like this one we haven’t updated yet. @maximmi is knocking them out so we can get this on his radar.

**Comment by deadlysyn** [comment]
Thanks for the response @osterman -- my bad, at first I just skimmed the PR list and thought "oh it's done" then I dug more into #12 after posting this and saw the issue + good work started by @masterpointio based on your suggestions.

I pulled Gowiem's branch last night and started poking at that tests. If I figure out what blocked him I'll share in #12 otherwise understand why we're waiting.
